// Constantes da aplicação xyMath - Foco em Matemática

export const ANO_SERIE_OPTIONS = [
  { value: '6º ano', label: '6º Ano - Fundamental II' },
  { value: '7º ano', label: '7º Ano - Fundamental II' },
  { value: '8º ano', label: '8º Ano - Fundamental II' },
  { value: '9º ano', label: '9º Ano - Fundamental II' },
  { value: '1ª série EM', label: '1ª Série - Ensino Médio' },
  { value: '2ª série EM', label: '2ª Série - Ensino Médio' },
  { value: '3ª série EM', label: '3ª Série - Ensino Médio' },
]

export const TURNO_OPTIONS = [
  { value: 'matutino', label: 'Matutino' },
  { value: 'vespertino', label: 'Vespertino' },
  { value: 'noturno', label: 'Noturno' },
  { value: 'integral', label: 'Integral' },
]

export const DIFICULDADE_OPTIONS = [
  { value: 'facil', label: 'Fácil' },
  { value: 'medio', label: 'Médio' },
  { value: 'dificil', label: 'Difícil' },
]

// Unidades Temáticas BNCC - Matemática
export const UNIDADES_TEMATICAS = [
  { value: 'numeros', label: 'Números' },
  { value: 'algebra', label: 'Álgebra' },
  { value: 'geometria', label: 'Geometria' },
  { value: 'grandezas_medidas', label: 'Grandezas e Medidas' },
  { value: 'probabilidade_estatistica', label: 'Probabilidade e Estatística' },
]

// Habilidades BNCC - Matemática Fundamental II (6º ao 9º ano)
export const HABILIDADES_BNCC_FUNDAMENTAL = {
  '6º ano': [
    { codigo: 'EF06MA01', descricao: 'Comparar, ordenar, ler e escrever números naturais e números racionais cuja representação decimal é finita, fazendo uso da reta numérica', unidade: 'numeros' },
    { codigo: 'EF06MA02', descricao: 'Reconhecer o sistema de numeração decimal, como o que prevaleceu no mundo ocidental, e destacar semelhanças e diferenças com outros sistemas', unidade: 'numeros' },
    { codigo: 'EF06MA03', descricao: 'Resolver e elaborar problemas que envolvam cálculos (mentais ou escritos, exatos ou aproximados) com números naturais', unidade: 'numeros' },
    { codigo: 'EF06MA04', descricao: 'Construir algoritmo em linguagem natural e representá-lo por fluxograma que indique a resolução de um problema simples', unidade: 'numeros' },
    { codigo: 'EF06MA05', descricao: 'Classificar números naturais em primos e compostos, estabelecer relações entre números, expressas pelos termos "é múltiplo de", "é divisor de", "é fator de"', unidade: 'numeros' },
    { codigo: 'EF06MA06', descricao: 'Resolver e elaborar problemas que envolvam as ideias de múltiplo e de divisor', unidade: 'numeros' },
    { codigo: 'EF06MA07', descricao: 'Compreender, comparar e ordenar frações associadas às ideias de partes de inteiros e resultado de divisão', unidade: 'numeros' },
    { codigo: 'EF06MA08', descricao: 'Reconhecer que os números racionais positivos podem ser expressos nas formas fracionária e decimal', unidade: 'numeros' },
    { codigo: 'EF06MA09', descricao: 'Resolver e elaborar problemas que envolvam o cálculo da fração de uma quantidade', unidade: 'numeros' },
    { codigo: 'EF06MA10', descricao: 'Resolver e elaborar problemas que envolvam adição ou subtração com números racionais positivos na representação fracionária', unidade: 'numeros' },
    { codigo: 'EF06MA11', descricao: 'Resolver e elaborar problemas com números racionais positivos na representação decimal', unidade: 'numeros' },
    { codigo: 'EF06MA12', descricao: 'Fazer estimativas de quantidades e aproximar números para múltiplos da potência de 10 mais próxima', unidade: 'numeros' },
    { codigo: 'EF06MA13', descricao: 'Resolver e elaborar problemas que envolvam porcentagens', unidade: 'numeros' },
    { codigo: 'EF06MA14', descricao: 'Reconhecer que a relação de igualdade matemática não se altera ao adicionar, subtrair, multiplicar ou dividir os seus dois membros por um mesmo número', unidade: 'algebra' },
    { codigo: 'EF06MA15', descricao: 'Resolver e elaborar problemas que envolvam a partilha de uma quantidade em duas partes desiguais', unidade: 'algebra' },
    { codigo: 'EF06MA16', descricao: 'Associar pares ordenados de números a pontos do plano cartesiano do 1º quadrante', unidade: 'algebra' },
    { codigo: 'EF06MA17', descricao: 'Quantificar e estabelecer relações entre o número de vértices, faces e arestas de prismas e pirâmides', unidade: 'geometria' },
    { codigo: 'EF06MA18', descricao: 'Reconhecer, nomear e comparar polígonos, considerando lados, vértices e ângulos', unidade: 'geometria' },
    { codigo: 'EF06MA19', descricao: 'Identificar características dos triângulos e classificá-los em relação às medidas dos lados e dos ângulos', unidade: 'geometria' },
    { codigo: 'EF06MA20', descricao: 'Identificar características dos quadriláteros, classificá-los em relação a lados e a ângulos', unidade: 'geometria' },
    { codigo: 'EF06MA21', descricao: 'Construir figuras planas semelhantes em situações de ampliação e de redução', unidade: 'geometria' },
    { codigo: 'EF06MA22', descricao: 'Utilizar instrumentos, como réguas e esquadros, ou softwares para representações de retas paralelas e perpendiculares', unidade: 'geometria' },
    { codigo: 'EF06MA23', descricao: 'Construir algoritmo para resolver situações passo a passo (como na construção de dobraduras ou na indicação de deslocamento de um objeto no plano)', unidade: 'geometria' },
    { codigo: 'EF06MA24', descricao: 'Resolver e elaborar problemas que envolvam as grandezas comprimento, massa, tempo, temperatura, área, capacidade e volume', unidade: 'grandezas_medidas' },
    { codigo: 'EF06MA25', descricao: 'Reconhecer a abertura do ângulo como grandeza associada às figuras geométricas', unidade: 'grandezas_medidas' },
    { codigo: 'EF06MA26', descricao: 'Resolver problemas que envolvam a noção de ângulo em diferentes contextos e em situações reais', unidade: 'grandezas_medidas' },
    { codigo: 'EF06MA27', descricao: 'Determinar medidas da abertura de ângulos, por meio de transferidor e/ou tecnologias digitais', unidade: 'grandezas_medidas' },
    { codigo: 'EF06MA28', descricao: 'Interpretar, descrever e desenhar plantas baixas simples de residências e vistas aéreas', unidade: 'grandezas_medidas' },
    { codigo: 'EF06MA29', descricao: 'Analisar e descrever mudanças que ocorrem no perímetro e na área de um quadrado ao se ampliarem ou reduzirem', unidade: 'grandezas_medidas' },
    { codigo: 'EF06MA30', descricao: 'Calcular a probabilidade de um evento aleatório, expressando-a por número racional', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF06MA31', descricao: 'Identificar as variáveis e suas frequências e os elementos constitutivos de diferentes tipos de gráficos', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF06MA32', descricao: 'Interpretar e resolver situações que envolvam dados de pesquisas sobre contextos ambientais, sustentabilidade, trânsito', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF06MA33', descricao: 'Planejar e coletar dados de pesquisa referente a práticas sociais escolhidas pelos alunos', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF06MA34', descricao: 'Interpretar e desenvolver fluxogramas simples, identificando as relações entre os objetos representados', unidade: 'probabilidade_estatistica' },
  ],
  '7º ano': [
    { codigo: 'EF07MA01', descricao: 'Resolver e elaborar problemas com números naturais, envolvendo as noções de divisor e de múltiplo', unidade: 'numeros' },
    { codigo: 'EF07MA02', descricao: 'Resolver e elaborar problemas que envolvam porcentagens', unidade: 'numeros' },
    { codigo: 'EF07MA03', descricao: 'Comparar e ordenar números inteiros em diferentes contextos, incluindo o histórico', unidade: 'numeros' },
    { codigo: 'EF07MA04', descricao: 'Resolver e elaborar problemas que envolvam operações com números inteiros', unidade: 'numeros' },
    { codigo: 'EF07MA05', descricao: 'Resolver um mesmo problema utilizando diferentes algoritmos', unidade: 'numeros' },
    { codigo: 'EF07MA06', descricao: 'Reconhecer que as resoluções de um grupo de problemas que têm a mesma estrutura podem ser obtidas utilizando os mesmos procedimentos', unidade: 'numeros' },
    { codigo: 'EF07MA07', descricao: 'Representar por meio de um fluxograma os passos utilizados para resolver um grupo de problemas', unidade: 'numeros' },
    { codigo: 'EF07MA08', descricao: 'Comparar e ordenar frações e números decimais em diferentes contextos', unidade: 'numeros' },
    { codigo: 'EF07MA09', descricao: 'Utilizar, na resolução de problemas, a associação entre razão e fração', unidade: 'numeros' },
    { codigo: 'EF07MA10', descricao: 'Comparar e ordenar números racionais em diferentes contextos e associá-los a pontos da reta numérica', unidade: 'numeros' },
    { codigo: 'EF07MA11', descricao: 'Compreender e utilizar a multiplicação e a divisão de números racionais, a relação entre elas e suas propriedades operatórias', unidade: 'numeros' },
    { codigo: 'EF07MA12', descricao: 'Resolver e elaborar problemas que envolvam as operações com números racionais', unidade: 'numeros' },
    { codigo: 'EF07MA13', descricao: 'Compreender a ideia de variável, representada por letra ou símbolo, para expressar relação entre duas grandezas', unidade: 'algebra' },
    { codigo: 'EF07MA14', descricao: 'Classificar sequências em recursivas e não recursivas, reconhecendo que o conceito de recursão está presente não apenas na matemática', unidade: 'algebra' },
    { codigo: 'EF07MA15', descricao: 'Utilizar a simbologia algébrica para expressar regularidades encontradas em sequências numéricas', unidade: 'algebra' },
    { codigo: 'EF07MA16', descricao: 'Reconhecer se duas expressões algébricas obtidas para descrever a regularidade de uma mesma sequência numérica são ou não equivalentes', unidade: 'algebra' },
    { codigo: 'EF07MA17', descricao: 'Resolver e elaborar problemas que envolvam variação de proporcionalidade direta e de proporcionalidade inversa entre duas grandezas', unidade: 'algebra' },
    { codigo: 'EF07MA18', descricao: 'Resolver e elaborar problemas que possam ser representados por equações polinomiais de 1º grau', unidade: 'algebra' },
    { codigo: 'EF07MA19', descricao: 'Realizar transformações de polígonos representados no plano cartesiano', unidade: 'geometria' },
    { codigo: 'EF07MA20', descricao: 'Reconhecer e representar, no plano cartesiano, o simétrico de figuras em relação aos eixos', unidade: 'geometria' },
    { codigo: 'EF07MA21', descricao: 'Reconhecer e construir figuras obtidas por simetrias de translação, rotação e reflexão', unidade: 'geometria' },
    { codigo: 'EF07MA22', descricao: 'Construir circunferências utilizando compasso ou softwares de geometria dinâmica', unidade: 'geometria' },
    { codigo: 'EF07MA23', descricao: 'Verificar relações entre os ângulos formados por retas paralelas cortadas por uma transversal', unidade: 'geometria' },
    { codigo: 'EF07MA24', descricao: 'Construir triângulos utilizando régua e compasso, reconhecendo a condição de existência do triângulo', unidade: 'geometria' },
    { codigo: 'EF07MA25', descricao: 'Reconhecer a rigidez geométrica dos triângulos e suas aplicações', unidade: 'geometria' },
    { codigo: 'EF07MA26', descricao: 'Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um triângulo', unidade: 'geometria' },
    { codigo: 'EF07MA27', descricao: 'Calcular medidas de ângulos internos de polígonos regulares', unidade: 'geometria' },
    { codigo: 'EF07MA28', descricao: 'Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um polígono regular', unidade: 'geometria' },
    { codigo: 'EF07MA29', descricao: 'Resolver e elaborar problemas que envolvam medidas de grandezas inseridos em contextos oriundos de situações cotidianas ou de outras áreas do conhecimento', unidade: 'grandezas_medidas' },
    { codigo: 'EF07MA30', descricao: 'Resolver e elaborar problemas de cálculo de medida do volume de blocos retangulares', unidade: 'grandezas_medidas' },
    { codigo: 'EF07MA31', descricao: 'Estabelecer expressões de cálculo de área de triângulos e de quadriláteros', unidade: 'grandezas_medidas' },
    { codigo: 'EF07MA32', descricao: 'Resolver e elaborar problemas de cálculo de medida de área de figuras planas', unidade: 'grandezas_medidas' },
    { codigo: 'EF07MA33', descricao: 'Estabelecer o número π como a razão entre a medida de uma circunferência e seu diâmetro', unidade: 'grandezas_medidas' },
    { codigo: 'EF07MA34', descricao: 'Resolver e elaborar problemas de cálculo de medida do comprimento da circunferência', unidade: 'grandezas_medidas' },
    { codigo: 'EF07MA35', descricao: 'Compreender, em contextos significativos, o significado de média estatística como indicador da tendência de uma pesquisa', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF07MA36', descricao: 'Planejar e realizar pesquisa envolvendo tema da realidade social, identificando a necessidade de ser censitária ou de usar amostra', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF07MA37', descricao: 'Interpretar e analisar dados apresentados em gráfico de setores divulgados pela mídia', unidade: 'probabilidade_estatistica' },
  ],
  '8º ano': [
    { codigo: 'EF08MA01', descricao: 'Efetuar cálculos com potências de expoentes inteiros e aplicar esse conhecimento na representação de números em notação científica', unidade: 'numeros' },
    { codigo: 'EF08MA02', descricao: 'Resolver e elaborar problemas usando a relação entre potenciação e radiciação, para representar uma raiz como potência de expoente fracionário', unidade: 'numeros' },
    { codigo: 'EF08MA03', descricao: 'Resolver e elaborar problemas de contagem cuja resolução envolva a aplicação do princípio multiplicativo', unidade: 'numeros' },
    { codigo: 'EF08MA04', descricao: 'Resolver e elaborar problemas, envolvendo cálculo de porcentagens, incluindo o uso de tecnologias digitais', unidade: 'numeros' },
    { codigo: 'EF08MA05', descricao: 'Reconhecer e utilizar procedimentos para a obtenção de uma fração geratriz para uma dízima periódica', unidade: 'numeros' },
    { codigo: 'EF08MA06', descricao: 'Resolver e elaborar problemas que envolvam cálculo do valor numérico de expressões algébricas', unidade: 'algebra' },
    { codigo: 'EF08MA07', descricao: 'Associar uma equação linear de 1º grau com duas incógnitas a uma reta no plano cartesiano', unidade: 'algebra' },
    { codigo: 'EF08MA08', descricao: 'Resolver e elaborar problemas relacionados ao seu contexto próximo, que possam ser representados por sistemas de equações de 1º grau', unidade: 'algebra' },
    { codigo: 'EF08MA09', descricao: 'Resolver e elaborar, com e sem uso de tecnologias, problemas que possam ser representados por equações polinomiais de 2º grau do tipo ax² = b', unidade: 'algebra' },
    { codigo: 'EF08MA10', descricao: 'Identificar a regularidade de uma sequência numérica ou figural não recursiva', unidade: 'algebra' },
    { codigo: 'EF08MA11', descricao: 'Identificar a regularidade de uma sequência numérica recursiva', unidade: 'algebra' },
    { codigo: 'EF08MA12', descricao: 'Identificar a natureza da variação de duas grandezas, diretamente, inversamente proporcionais ou não proporcionais', unidade: 'algebra' },
    { codigo: 'EF08MA13', descricao: 'Resolver e elaborar problemas que envolvam grandezas diretamente ou inversamente proporcionais', unidade: 'algebra' },
    { codigo: 'EF08MA14', descricao: 'Demonstrar propriedades de quadriláteros por meio da identificação da congruência de triângulos', unidade: 'geometria' },
    { codigo: 'EF08MA15', descricao: 'Construir, utilizando instrumentos de desenho ou softwares de geometria dinâmica, mediatriz, bissetriz, ângulos de 90°, 60°, 45° e 30°', unidade: 'geometria' },
    { codigo: 'EF08MA16', descricao: 'Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um hexágono regular', unidade: 'geometria' },
    { codigo: 'EF08MA17', descricao: 'Aplicar os conceitos de mediatriz e bissetriz como lugares geométricos na resolução de problemas', unidade: 'geometria' },
    { codigo: 'EF08MA18', descricao: 'Reconhecer e construir figuras obtidas por composições de transformações geométricas', unidade: 'geometria' },
    { codigo: 'EF08MA19', descricao: 'Resolver e elaborar problemas que envolvam medidas de área de figuras geométricas', unidade: 'grandezas_medidas' },
    { codigo: 'EF08MA20', descricao: 'Reconhecer a relação entre um litro e um decímetro cúbico e a relação entre litro e metro cúbico', unidade: 'grandezas_medidas' },
    { codigo: 'EF08MA21', descricao: 'Resolver e elaborar problemas que envolvam o cálculo do volume de recipiente cujo formato é o de um bloco retangular', unidade: 'grandezas_medidas' },
    { codigo: 'EF08MA22', descricao: 'Calcular a probabilidade de eventos, com base na construção do espaço amostral, utilizando o princípio multiplicativo', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF08MA23', descricao: 'Avaliar a adequação de diferentes tipos de gráficos para representar um conjunto de dados', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF08MA24', descricao: 'Classificar as frequências de uma variável contínua de uma pesquisa em classes', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF08MA25', descricao: 'Obter os valores de medidas de tendência central de uma pesquisa estatística', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF08MA26', descricao: 'Selecionar razões, de diferentes naturezas, que justifiquem a tomada de decisões em problemas do cotidiano', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF08MA27', descricao: 'Planejar e executar pesquisa amostral, apresentando relatório que contemple medidas de tendência central', unidade: 'probabilidade_estatistica' },
  ],
  '9º ano': [
    { codigo: 'EF09MA01', descricao: 'Reconhecer que, uma vez fixada uma unidade de comprimento, existem segmentos de reta cujo comprimento não é expresso por número racional', unidade: 'numeros' },
    { codigo: 'EF09MA02', descricao: 'Reconhecer um número irracional como um número real cuja representação decimal é infinita e não periódica', unidade: 'numeros' },
    { codigo: 'EF09MA03', descricao: 'Efetuar cálculos com números reais, inclusive potências com expoentes fracionários', unidade: 'numeros' },
    { codigo: 'EF09MA04', descricao: 'Resolver e elaborar problemas com números reais, inclusive em notação científica', unidade: 'numeros' },
    { codigo: 'EF09MA05', descricao: 'Resolver e elaborar problemas que envolvam porcentagens, com a ideia de aplicação de percentuais sucessivos', unidade: 'numeros' },
    { codigo: 'EF09MA06', descricao: 'Compreender as funções como relações de dependência unívoca entre duas variáveis', unidade: 'algebra' },
    { codigo: 'EF09MA07', descricao: 'Resolver problemas que envolvam a razão entre duas grandezas de espécies diferentes', unidade: 'algebra' },
    { codigo: 'EF09MA08', descricao: 'Resolver e elaborar problemas que envolvam relações de proporcionalidade direta e inversa entre duas ou mais grandezas', unidade: 'algebra' },
    { codigo: 'EF09MA09', descricao: 'Compreender os processos de fatoração de expressões algébricas, com base em suas relações com os produtos notáveis', unidade: 'algebra' },
    { codigo: 'EF09MA10', descricao: 'Resolver problemas que envolvam grandezas diretamente ou inversamente proporcionais por meio de estratégias variadas', unidade: 'algebra' },
    { codigo: 'EF09MA11', descricao: 'Resolver problemas por meio do estabelecimento de relações entre arcos, ângulos centrais e ângulos inscritos na circunferência', unidade: 'geometria' },
    { codigo: 'EF09MA12', descricao: 'Reconhecer as condições necessárias e suficientes para que dois triângulos sejam semelhantes', unidade: 'geometria' },
    { codigo: 'EF09MA13', descricao: 'Demonstrar relações métricas do triângulo retângulo, entre elas o teorema de Pitágoras', unidade: 'geometria' },
    { codigo: 'EF09MA14', descricao: 'Resolver e elaborar problemas de aplicação do teorema de Pitágoras ou das relações de proporcionalidade envolvendo retas paralelas', unidade: 'geometria' },
    { codigo: 'EF09MA15', descricao: 'Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um polígono regular cuja medida do lado é conhecida', unidade: 'geometria' },
    { codigo: 'EF09MA16', descricao: 'Determinar o ponto médio de um segmento de reta e a distância entre dois pontos quaisquer no plano cartesiano', unidade: 'geometria' },
    { codigo: 'EF09MA17', descricao: 'Reconhecer vistas ortogonais de figuras espaciais e aplicar esse conhecimento para desenhar objetos', unidade: 'geometria' },
    { codigo: 'EF09MA18', descricao: 'Reconhecer e empregar unidades usadas para expressar medidas muito grandes ou muito pequenas', unidade: 'grandezas_medidas' },
    { codigo: 'EF09MA19', descricao: 'Resolver e elaborar problemas que envolvam medidas de volumes de prismas e de cilindros retos', unidade: 'grandezas_medidas' },
    { codigo: 'EF09MA20', descricao: 'Reconhecer, em contextos cotidianos, funções lineares e/ou afins, em suas representações algébrica e gráfica', unidade: 'algebra' },
    { codigo: 'EF09MA21', descricao: 'Analisar e identificar, em gráficos divulgados pela mídia, parsing de funções do 1º grau', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF09MA22', descricao: 'Escolher e construir o gráfico mais adequado para apresentar um determinado conjunto de dados', unidade: 'probabilidade_estatistica' },
    { codigo: 'EF09MA23', descricao: 'Planejar e executar pesquisa amostral envolvendo tema da realidade social', unidade: 'probabilidade_estatistica' },
  ],
}

// Habilidades BNCC - Matemática Ensino Médio
export const HABILIDADES_BNCC_MEDIO = {
  '1ª série EM': [
    { codigo: 'EM13MAT101', descricao: 'Interpretar criticamente situações econômicas, sociais e fatos relativos às Ciências da Natureza que envolvam a variação de grandezas', unidade: 'numeros' },
    { codigo: 'EM13MAT102', descricao: 'Analisar tabelas, gráficos e amostras de pesquisas estatísticas apresentadas em relatórios divulgados por diferentes meios de comunicação', unidade: 'probabilidade_estatistica' },
    { codigo: 'EM13MAT103', descricao: 'Interpretar e compreender textos científicos ou divulgados pelas mídias, que empregam unidades de medida de diferentes grandezas', unidade: 'grandezas_medidas' },
    { codigo: 'EM13MAT104', descricao: 'Interpretar taxas e índices de natureza socioeconômica, investigando os processos de cálculo desses números', unidade: 'numeros' },
    { codigo: 'EM13MAT105', descricao: 'Utilizar as noções de transformações isométricas para construir figuras congruentes', unidade: 'geometria' },
    { codigo: 'EM13MAT106', descricao: 'Identificar situações da vida cotidiana nas quais seja necessário fazer escolhas levando-se em conta os riscos probabilísticos', unidade: 'probabilidade_estatistica' },
    { codigo: 'EM13MAT301', descricao: 'Resolver e elaborar problemas do cotidiano, da Matemática e de outras áreas do conhecimento, que envolvem equações lineares simultâneas', unidade: 'algebra' },
    { codigo: 'EM13MAT302', descricao: 'Construir modelos empregando as funções polinomiais de 1º ou 2º graus', unidade: 'algebra' },
    { codigo: 'EM13MAT303', descricao: 'Interpretar e comparar situações que envolvam juros simples com as que envolvem juros compostos', unidade: 'numeros' },
    { codigo: 'EM13MAT304', descricao: 'Resolver e elaborar problemas com funções exponenciais nos quais seja necessário compreender e interpretar a variação das grandezas envolvidas', unidade: 'algebra' },
    { codigo: 'EM13MAT305', descricao: 'Resolver e elaborar problemas com funções logarítmicas nos quais seja necessário compreender e interpretar a variação das grandezas envolvidas', unidade: 'algebra' },
    { codigo: 'EM13MAT306', descricao: 'Resolver e elaborar problemas em contextos que envolvem fenômenos periódicos reais', unidade: 'algebra' },
    { codigo: 'EM13MAT307', descricao: 'Empregar diferentes métodos para a obtenção da medida da área de uma superfície', unidade: 'grandezas_medidas' },
    { codigo: 'EM13MAT308', descricao: 'Aplicar as relações métricas, incluindo as leis do seno e do cosseno ou as noções de congruência e semelhança', unidade: 'geometria' },
    { codigo: 'EM13MAT309', descricao: 'Resolver e elaborar problemas que envolvem o cálculo de áreas totais e de volumes de prismas, pirâmides e corpos redondos', unidade: 'grandezas_medidas' },
    { codigo: 'EM13MAT310', descricao: 'Resolver e elaborar problemas de contagem envolvendo agrupamentos ordenáveis ou não de elementos', unidade: 'probabilidade_estatistica' },
    { codigo: 'EM13MAT311', descricao: 'Identificar e descrever o espaço amostral de eventos aleatórios, realizando contagem das possibilidades', unidade: 'probabilidade_estatistica' },
    { codigo: 'EM13MAT312', descricao: 'Resolver e elaborar problemas que envolvem o cálculo de probabilidade de eventos em experimentos aleatórios sucessivos', unidade: 'probabilidade_estatistica' },
    { codigo: 'EM13MAT313', descricao: 'Utilizar, quando necessário, a média ponderada para avaliar e analisar um conjunto de dados', unidade: 'probabilidade_estatistica' },
    { codigo: 'EM13MAT314', descricao: 'Resolver e elaborar problemas que envolvem grandezas determinadas pela razão ou pelo produto de outras', unidade: 'algebra' },
    { codigo: 'EM13MAT315', descricao: 'Investigar e registrar, por meio de um fluxograma, uma sequência de passos necessários para resolver um problema', unidade: 'algebra' },
    { codigo: 'EM13MAT316', descricao: 'Resolver e elaborar problemas, em diferentes contextos, que envolvem cálculo e interpretação das medidas de tendência central', unidade: 'probabilidade_estatistica' },
  ],
  '2ª série EM': [
    { codigo: 'EM13MAT201', descricao: 'Propor ou participar de ações adequadas às demandas da região, preferencialmente para sua comunidade, envolvendo medições e cálculos de perímetro, de área, de volume, de capacidade ou de massa', unidade: 'grandezas_medidas' },
    { codigo: 'EM13MAT202', descricao: 'Planejar e executar pesquisa amostral sobre questões relevantes, usando dados coletados diretamente ou em diferentes fontes', unidade: 'probabilidade_estatistica' },
    { codigo: 'EM13MAT203', descricao: 'Aplicar conceitos matemáticos no planejamento, na execução e na análise de ações envolvendo a utilização de aplicativos e a criação de planilhas', unidade: 'algebra' },
    { codigo: 'EM13MAT401', descricao: 'Converter representações algébricas de funções polinomiais de 1º grau em representações geométricas no plano cartesiano', unidade: 'algebra' },
    { codigo: 'EM13MAT402', descricao: 'Converter representações algébricas de funções polinomiais de 2º grau em representações geométricas no plano cartesiano', unidade: 'algebra' },
    { codigo: 'EM13MAT403', descricao: 'Analisar e estabelecer relações, com ou sem apoio de tecnologias digitais, entre as representações de funções exponencial e logarítmica', unidade: 'algebra' },
    { codigo: 'EM13MAT404', descricao: 'Analisar funções definidas por uma ou mais sentenças, em suas representações algébrica e gráfica', unidade: 'algebra' },
    { codigo: 'EM13MAT405', descricao: 'Utilizar conceitos iniciais de uma linguagem de programação na implementação de algoritmos escritos em linguagem corrente', unidade: 'algebra' },
    { codigo: 'EM13MAT406', descricao: 'Construir e interpretar tabelas e gráficos de frequências com base em dados obtidos em pesquisas por amostras estatísticas', unidade: 'probabilidade_estatistica' },
    { codigo: 'EM13MAT407', descricao: 'Interpretar e comparar conjuntos de dados estatísticos por meio de diferentes diagramas e gráficos', unidade: 'probabilidade_estatistica' },
  ],
  '3ª série EM': [
    { codigo: 'EM13MAT501', descricao: 'Investigar relações entre números expressos em tabelas para representá-los no plano cartesiano, identificando padrões e criando conjecturas para generalizar e expressar algebricamente essa generalização', unidade: 'algebra' },
    { codigo: 'EM13MAT502', descricao: 'Investigar relações entre números expressos em tabelas para representá-los no plano cartesiano, identificando padrões e criando conjecturas para generalizar e expressar algebricamente essa generalização, reconhecendo quando essa expression corresponde a uma função polinomial de 1º grau', unidade: 'algebra' },
    { codigo: 'EM13MAT503', descricao: 'Investigar pontos de máximo ou de mínimo de funções quadráticas em contextos envolvendo superfícies, Matemática Financeira ou Cinemática', unidade: 'algebra' },
    { codigo: 'EM13MAT504', descricao: 'Investigar processos de obtenção da medida do volume de prismas, pirâmides, cilindros e cones, incluindo a composição de um ou mais desses', unidade: 'grandezas_medidas' },
    { codigo: 'EM13MAT505', descricao: 'Resolver problemas sobre ladrilhamento do plano, com ou sem apoio de aplicativos de geometria dinâmica', unidade: 'geometria' },
    { codigo: 'EM13MAT506', descricao: 'Representar graficamente a variação da área e do perímetro de um polígono regular quando os comprimentos de seus lados variam', unidade: 'geometria' },
    { codigo: 'EM13MAT507', descricao: 'Identificar e associar progressões aritméticas (PA) a funções afins de domínios discretos, para análise de propriedades', unidade: 'algebra' },
    { codigo: 'EM13MAT508', descricao: 'Identificar e associar progressões geométricas (PG) a funções exponenciais de domínios discretos, para análise de propriedades', unidade: 'algebra' },
    { codigo: 'EM13MAT509', descricao: 'Investigar a deformação de ângulos e áreas provocada pelas diferentes projeções usadas em cartografia', unidade: 'geometria' },
    { codigo: 'EM13MAT510', descricao: 'Investigar conjuntos de dados relativos ao comportamento de duas variáveis numéricas, usando ou não tecnologias da informação', unidade: 'probabilidade_estatistica' },
    { codigo: 'EM13MAT511', descricao: 'Resolver problemas que envolvam os conceitos de permutação e combinação', unidade: 'probabilidade_estatistica' },
  ],
}

// Descritores SAEB - Matemática
export const DESCRITORES_SAEB = {
  'fundamental': [
    // Espaço e Forma
    { codigo: 'D1', descricao: 'Identificar a localização/movimentação de objeto em mapas, croquis e outras representações gráficas', tema: 'Espaço e Forma' },
    { codigo: 'D2', descricao: 'Identificar propriedades comuns e diferenças entre poliedros e corpos redondos, relacionando figuras tridimensionais com suas planificações', tema: 'Espaço e Forma' },
    { codigo: 'D3', descricao: 'Identificar propriedades comuns e diferenças entre figuras bidimensionais pelo número de lados, pelos tipos de ângulos', tema: 'Espaço e Forma' },
    { codigo: 'D4', descricao: 'Identificar relação entre quadriláteros por meio de suas propriedades', tema: 'Espaço e Forma' },
    { codigo: 'D5', descricao: 'Reconhecer a conservação ou modificação de medidas dos lados, do perímetro, da área em ampliação e/ou redução de figuras poligonais', tema: 'Espaço e Forma' },
    { codigo: 'D6', descricao: 'Reconhecer ângulos como mudança de direção ou giros, identificando ângulos retos e não-retos', tema: 'Espaço e Forma' },
    { codigo: 'D7', descricao: 'Reconhecer que as imagens de uma figura construída por uma transformação homotética são semelhantes', tema: 'Espaço e Forma' },
    { codigo: 'D8', descricao: 'Resolver problema utilizando a propriedade dos polígonos (soma de seus ângulos internos, número de diagonais, cálculo da medida de cada ângulo interno nos polígonos regulares)', tema: 'Espaço e Forma' },
    { codigo: 'D9', descricao: 'Interpretar informações apresentadas por meio de coordenadas cartesianas', tema: 'Espaço e Forma' },
    { codigo: 'D10', descricao: 'Utilizar relações métricas do triângulo retângulo para resolver problemas significativos', tema: 'Espaço e Forma' },
    { codigo: 'D11', descricao: 'Reconhecer círculo/circunferência, seus elementos e algumas de suas relações', tema: 'Espaço e Forma' },
    // Grandezas e Medidas
    { codigo: 'D12', descricao: 'Resolver problema envolvendo o cálculo de perímetro de figuras planas', tema: 'Grandezas e Medidas' },
    { codigo: 'D13', descricao: 'Resolver problema envolvendo o cálculo de área de figuras planas', tema: 'Grandezas e Medidas' },
    { codigo: 'D14', descricao: 'Resolver problema envolvendo noções de volume', tema: 'Grandezas e Medidas' },
    { codigo: 'D15', descricao: 'Resolver problema envolvendo relações entre diferentes unidades de medida', tema: 'Grandezas e Medidas' },
    // Números e Operações/Álgebra e Funções
    { codigo: 'D16', descricao: 'Identificar a localização de números inteiros na reta numérica', tema: 'Números e Operações' },
    { codigo: 'D17', descricao: 'Identificar a localização de números racionais na reta numérica', tema: 'Números e Operações' },
    { codigo: 'D18', descricao: 'Efetuar cálculos com números inteiros, envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação)', tema: 'Números e Operações' },
    { codigo: 'D19', descricao: 'Resolver problema com números naturais, envolvendo diferentes significados das operações (adição, subtração, multiplicação, divisão, potenciação)', tema: 'Números e Operações' },
    { codigo: 'D20', descricao: 'Resolver problema com números inteiros envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação)', tema: 'Números e Operações' },
    { codigo: 'D21', descricao: 'Reconhecer as diferentes representações de um número racional', tema: 'Números e Operações' },
    { codigo: 'D22', descricao: 'Identificar fração como representação que pode estar associada a diferentes significados', tema: 'Números e Operações' },
    { codigo: 'D23', descricao: 'Identificar frações equivalentes', tema: 'Números e Operações' },
    { codigo: 'D24', descricao: 'Reconhecer as representações decimais dos números racionais como uma extensão do sistema de numeração decimal', tema: 'Números e Operações' },
    { codigo: 'D25', descricao: 'Efetuar cálculos que envolvam operações com números racionais (adição, subtração, multiplicação, divisão, potenciação)', tema: 'Números e Operações' },
    { codigo: 'D26', descricao: 'Resolver problema com números racionais envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação)', tema: 'Números e Operações' },
    { codigo: 'D27', descricao: 'Efetuar cálculos simples com valores aproximados de radicais', tema: 'Números e Operações' },
    { codigo: 'D28', descricao: 'Resolver problema que envolva porcentagem', tema: 'Números e Operações' },
    { codigo: 'D29', descricao: 'Resolver problema que envolva variações proporcionais, diretas ou inversas, entre grandezas', tema: 'Números e Operações' },
    { codigo: 'D30', descricao: 'Calcular o valor numérico de uma expressão algébrica', tema: 'Álgebra e Funções' },
    { codigo: 'D31', descricao: 'Resolver problema que envolva equação de 2º grau', tema: 'Álgebra e Funções' },
    { codigo: 'D32', descricao: 'Identificar a expressão algébrica que expressa uma regularidade observada em sequências de números ou figuras', tema: 'Álgebra e Funções' },
    { codigo: 'D33', descricao: 'Identificar uma equação ou inequação de 1º grau que expressa um problema', tema: 'Álgebra e Funções' },
    { codigo: 'D34', descricao: 'Identificar um sistema de equações do 1º grau que expressa um problema', tema: 'Álgebra e Funções' },
    { codigo: 'D35', descricao: 'Identificar a relação entre as representações algébrica e geométrica de um sistema de equações de 1º grau', tema: 'Álgebra e Funções' },
    // Tratamento da Informação
    { codigo: 'D36', descricao: 'Resolver problema envolvendo informações apresentadas em tabelas e/ou gráficos', tema: 'Tratamento da Informação' },
    { codigo: 'D37', descricao: 'Associar informações apresentadas em listas e/ou tabelas simples aos gráficos que as representam e vice-versa', tema: 'Tratamento da Informação' },
    { codigo: 'D38', descricao: 'Resolver problema que envolva medidas de tendência central (média, mediana, moda)', tema: 'Tratamento da Informação' },
  ],
  'medio': [
    // Espaço e Forma
    { codigo: 'D1', descricao: 'Identificar figuras semelhantes mediante o reconhecimento de relações de proporcionalidade', tema: 'Espaço e Forma' },
    { codigo: 'D2', descricao: 'Reconhecer aplicações das relações métricas do triângulo retângulo em um problema que envolva figuras planas ou espaciais', tema: 'Espaço e Forma' },
    { codigo: 'D3', descricao: 'Relacionar diferentes poliedros ou corpos redondos com suas planificações ou vistas', tema: 'Espaço e Forma' },
    { codigo: 'D4', descricao: 'Identificar a relação entre o número de vértices, faces e/ou arestas de poliedros expressa em um problema', tema: 'Espaço e Forma' },
    { codigo: 'D5', descricao: 'Resolver problema que envolva razões trigonométricas no triângulo retângulo (seno, cosseno, tangente)', tema: 'Espaço e Forma' },
    { codigo: 'D6', descricao: 'Identificar a localização de pontos no plano cartesiano', tema: 'Espaço e Forma' },
    { codigo: 'D7', descricao: 'Interpretar geometricamente os coeficientes da equação de uma reta', tema: 'Espaço e Forma' },
    { codigo: 'D8', descricao: 'Identificar a equação de uma reta apresentada a partir de dois pontos dados ou de um ponto e sua inclinação', tema: 'Espaço e Forma' },
    { codigo: 'D9', descricao: 'Relacionar a determinação do ponto de interseção de duas retas com a resolução de um sistema de equações', tema: 'Espaço e Forma' },
    { codigo: 'D10', descricao: 'Reconhecer, dentre as equações de 2º grau com duas incógnitas, as que representam circunferências', tema: 'Espaço e Forma' },
    // Grandezas e Medidas
    { codigo: 'D11', descricao: 'Resolver problema envolvendo o cálculo de perímetro de figuras planas', tema: 'Grandezas e Medidas' },
    { codigo: 'D12', descricao: 'Resolver problema envolvendo o cálculo de área de figuras planas', tema: 'Grandezas e Medidas' },
    { codigo: 'D13', descricao: 'Resolver problema envolvendo a área total e/ou volume de um sólido (prisma, pirâmide, cilindro, cone, esfera)', tema: 'Grandezas e Medidas' },
    // Números e Operações/Álgebra e Funções
    { codigo: 'D14', descricao: 'Identificar a localização de números reais na reta numérica', tema: 'Números e Operações' },
    { codigo: 'D15', descricao: 'Resolver problema que envolva variação proporcional, direta ou inversa, entre grandezas', tema: 'Números e Operações' },
    { codigo: 'D16', descricao: 'Resolver problema que envolva porcentagem', tema: 'Números e Operações' },
    { codigo: 'D17', descricao: 'Resolver problema envolvendo equação de 2º grau', tema: 'Álgebra e Funções' },
    { codigo: 'D18', descricao: 'Reconhecer expressão algébrica que representa uma função a partir de uma tabela', tema: 'Álgebra e Funções' },
    { codigo: 'D19', descricao: 'Resolver problema envolvendo uma função de 1º grau', tema: 'Álgebra e Funções' },
    { codigo: 'D20', descricao: 'Analisar crescimento/decrescimento, zeros de funções reais apresentadas em gráficos', tema: 'Álgebra e Funções' },
    { codigo: 'D21', descricao: 'Identificar o gráfico que representa uma situação descrita em um texto', tema: 'Álgebra e Funções' },
    { codigo: 'D22', descricao: 'Resolver problema envolvendo P.A./P.G. dada a fórmula do termo geral', tema: 'Álgebra e Funções' },
    { codigo: 'D23', descricao: 'Reconhecer o gráfico de uma função polinomial de 1º grau por meio de seus coeficientes', tema: 'Álgebra e Funções' },
    { codigo: 'D24', descricao: 'Reconhecer a representação algébrica de uma função do 1º grau, dado o seu gráfico', tema: 'Álgebra e Funções' },
    { codigo: 'D25', descricao: 'Resolver problemas que envolvam os pontos de máximo ou de mínimo no gráfico de uma função de 2º grau', tema: 'Álgebra e Funções' },
    { codigo: 'D26', descricao: 'Relacionar as raízes de um polinômio com sua decomposição em fatores do 1º grau', tema: 'Álgebra e Funções' },
    { codigo: 'D27', descricao: 'Identificar a representação algébrica e/ou gráfica de uma função exponencial', tema: 'Álgebra e Funções' },
    { codigo: 'D28', descricao: 'Identificar a representação algébrica e/ou gráfica de uma função logarítmica', tema: 'Álgebra e Funções' },
    { codigo: 'D29', descricao: 'Resolver problema que envolva função exponencial', tema: 'Álgebra e Funções' },
    { codigo: 'D30', descricao: 'Identificar gráficos de funções trigonométricas (seno, cosseno, tangente) reconhecendo suas propriedades', tema: 'Álgebra e Funções' },
    // Tratamento da Informação
    { codigo: 'D31', descricao: 'Determinar a probabilidade de ocorrência de um evento', tema: 'Tratamento da Informação' },
    { codigo: 'D32', descricao: 'Resolver problema de contagem utilizando o princípio multiplicativo ou noções de permutação simples e/ou combinação simples', tema: 'Tratamento da Informação' },
    { codigo: 'D33', descricao: 'Calcular a probabilidade de ocorrência de um evento', tema: 'Tratamento da Informação' },
    { codigo: 'D34', descricao: 'Resolver problema envolvendo informações apresentadas em tabelas e/ou gráficos', tema: 'Tratamento da Informação' },
    { codigo: 'D35', descricao: 'Associar informações apresentadas em listas e/ou tabelas simples aos gráficos que as representam e vice-versa', tema: 'Tratamento da Informação' },
  ],
}

// Função auxiliar para obter todas as habilidades por ano
export function getHabilidadesPorAno(ano: string) {
  if (ano.includes('EM')) {
    return HABILIDADES_BNCC_MEDIO[ano as keyof typeof HABILIDADES_BNCC_MEDIO] || []
  }
  return HABILIDADES_BNCC_FUNDAMENTAL[ano as keyof typeof HABILIDADES_BNCC_FUNDAMENTAL] || []
}

// Função auxiliar para obter descritores por nível
export function getDescritoresPorNivel(nivel: 'fundamental' | 'medio') {
  return DESCRITORES_SAEB[nivel] || []
}

// Função para determinar o nível baseado no ano
export function getNivel(ano: string): 'fundamental' | 'medio' {
  return ano.includes('EM') ? 'medio' : 'fundamental'
}
